from __future__ import annotations


def build_prompt(model_name: str, clinical_note: str, guideline_text: str) -> str:
    model_name_normalized = (model_name or "").strip().lower()
    base_prompt = (
        "Clinical note:\n"
        f"{clinical_note}\n\n"
        "Annotation guideline:\n"
        f"{guideline_text}\n\n"
        "Return JSON only as a single JSON array. Each array element must be a document object with "
        "id, data, annotations, and predictions. Use only entity labels, relation labels, and assertion "
        "labels from the guideline.\n"
        "Do not invent unsupported labels, relations, or assertion statuses.\n"
        "The predictions array should contain a result list with entity items of type 'labels', "
        "relation items of type 'relation', and assertion items of type 'labels'.\n"
        "This is the John Snow Labs (Generative AI Lab / NLP Lab) supported prediction format: assertion "
        "status is represented as its own result item, separate from the entity item it applies to. "
        "An assertion item has from_name 'assertion', to_name 'text', type 'labels', and a value with the "
        "same start, end, and text as the entity span it is attached to, plus a labels array containing a "
        "single assertion status (e.g. Present, Absent, Possible, Conditional, Hypothetical, "
        "Associated_With_Someone_Else) taken from the guideline.\n"
        "Only add an assertion item for entity types that the guideline defines an assertion status for. "
        "Do not add assertion items for entities without a defined assertion status, and do not attach more "
        "than one assertion status to the same entity span.\n"
        "Example output format:\n"
        "[\n"
        "  {\n"
        "    \"id\": 1001,\n"
        "    \"data\": {\"text\": \"The patient was prescribed Metformin 500mg daily for diabetes.\"},\n"
        "    \"annotations\": [],\n"
        "    \"predictions\": [\n"
        "      {\n"
        "        \"id\": \"pred_set_771\",\n"
        "        \"model_version\": \"healthcare_relation_extraction_v3\",\n"
        "        \"score\": 0.89,\n"
        "        \"result\": [\n"
        "          {\n"
        "            \"id\": \"pred_chunk_01\",\n"
        "            \"from_name\": \"label\",\n"
        "            \"to_name\": \"text\",\n"
        "            \"type\": \"labels\",\n"
        "            \"value\": {\n"
        "              \"start\": 27,\n"
        "              \"end\": 36,\n"
        "              \"text\": \"Metformin\",\n"
        "              \"labels\": [\"DRUG\"]\n"
        "            }\n"
        "          },\n"
        "          {\n"
        "            \"id\": \"pred_chunk_02\",\n"
        "            \"from_name\": \"label\",\n"
        "            \"to_name\": \"text\",\n"
        "            \"type\": \"labels\",\n"
        "            \"value\": {\n"
        "              \"start\": 37,\n"
        "              \"end\": 42,\n"
        "              \"text\": \"500mg\",\n"
        "              \"labels\": [\"DOSAGE\"]\n"
        "            }\n"
        "          },\n"
        "          {\n"
        "            \"id\": \"pred_chunk_03\",\n"
        "            \"from_name\": \"label\",\n"
        "            \"to_name\": \"text\",\n"
        "            \"type\": \"labels\",\n"
        "            \"value\": {\n"
        "              \"start\": 53,\n"
        "              \"end\": 61,\n"
        "              \"text\": \"diabetes\",\n"
        "              \"labels\": [\"PROBLEM\"]\n"
        "            }\n"
        "          },\n"
        "          {\n"
        "            \"id\": \"pred_assertion_01\",\n"
        "            \"from_name\": \"assertion\",\n"
        "            \"to_name\": \"text\",\n"
        "            \"type\": \"labels\",\n"
        "            \"value\": {\n"
        "              \"start\": 53,\n"
        "              \"end\": 61,\n"
        "              \"text\": \"diabetes\",\n"
        "              \"labels\": [\"Present\"]\n"
        "            }\n"
        "          },\n"
        "          {\n"
        "            \"id\": \"pred_rel_01\",\n"
        "            \"from_id\": \"pred_chunk_01\",\n"
        "            \"to_id\": \"pred_chunk_02\",\n"
        "            \"type\": \"relation\",\n"
        "            \"labels\": [\"IS_DOSAGE_OF\"],\n"
        "            \"score\": 0.92\n"
        "          }\n"
        "        ]\n"
        "      }\n"
        "    ]\n"
        "  }\n"
        "]"
    )

    if model_name_normalized.startswith("gpt"):
        return base_prompt + "\nUse concise but accurate extraction."
    if "mistral" in model_name_normalized:
        return base_prompt + "\nBe strict about label names and avoid unsupported relations."
    if "claude" in model_name_normalized:
        return base_prompt + "\nUse concise but accurate extraction."
    return base_prompt
